### ISSUE TITLE
Is that a bug? PID and delay system.

### ISSUE THREAD

**Issue by phelipe** [JuliaControl/ControlSystems.jl#232]
The following code works as usual:
```
julia> G3 =  tf(1, [1., 2., 0]);
julia> system = feedback( pid( kp = 10, kd = 3) * G3)
julia> stepplot( system )
```
But entering a delay returns an error even if the delay is 0 seconds:

```
julia> G3 = delay(0.) * tf(1, [1., 2., 0]);
julia> system = feedback( pid( kp = 10, kd = 3) * G3)
julia> stepplot( system )

System is improper, a state-space representation is impossible
```

**Comment by mfalt** [comment]
The problem occurs already at trying to convert `pid( kp = 10, kd = 3)` to a State Space representation. Since all delay systems are represented in StateSpace form, the connection of the systems needs to be in state space form, and therefore we get a problem when trying to promote the PD controller to StateSpace.

The same problem occurs here:
```julia
G3 =  ss(tf(1, [1., 2., 0]));
system = feedback( pid( kp = 10, kd = 3) * G3)
stepplot( system )
``` 

The only solution I can think of here is to add a quick filter
```julia
G3 = delay(0.) * tf(1, [1., 2., 0]);
filter = 1/(0.01*tf("s")+1)
system = feedback( pid( kp = 10, kd = 3)* filter * G3, 1)
stepplot( system )
``` 

The `feedback(sys, 1)` is needed since we don't seem to have a fallback for `feedback(sys)`, I will fix this immediately. There seems to be some numerical problems with the simulation when the speed of the filter is too fast and the system is in StateSpace form, I will try to investigate this further.

**Comment by phelipe** [comment]
Thanks! Sorry for the delay in replying. I will try to implement something similar to what is done with scilab to "convert" the PID into a state space model.
