### ISSUE TITLE
LFT doesn't give results as in K. Zhou, J. Doyle

### ISSUE THREAD

**Issue by CompleteMetricSpace** [JuliaControl/ControlSystems.jl#577]
Upper LFT of a 3x3 system and a 2x1 system gives a 2x2 system, even though it should be (by definition in the mentioned book) a 1x2 system:
```
julia> G = ss([1],[1 2 3],[1;2;3],zeros(3,3));
julia> Delta = ss([1],[1],[1;2],[1;2]);  
julia> lft(G,Delta,:u)  
StateSpace{Continuous, Float64}  
A = 
 6.0  5.0
 1.0  1.0
B = 
 2.0  3.0
 0.0  0.0
C = 
 2.0  0.0
 3.0  0.0
D = 
 0.0  0.0
 0.0  0.0
```
I think the bug is in the function `feedback`, where the unknown channel sizes are initialized by default to the colon `:`.
This happens in v0.11.1

**Comment by olof3** [comment]
Sorry about that. It seems like the problem was that the `lft` function called the `feedback` function in a completely wrong way.

I hope that the #578 resolves the problem. If you do some more experiments to ensure that it works, it would be nice to add those to the CI tests, in #578 I only got around to add one new test for upper and one for lower lft.
